import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, ChevronUp } from 'lucide-react';

const faqItems = [
  {
    id: 1,
    question: "How are carbon credits generated by BeeCarbonit systems?",
    answer: "BeeCarbonit systems generate verifiable carbon credits through real-time monitoring of emissions reduction and energy optimization within our managed facilities. These credits are registered on a secure blockchain ledger, ensuring transparency and integrity."
  },
  {
    id: 2,
    question: "What facilities are currently managed by BeeCarbonit?",
    answer: "We manage a wide range of facilities including corporate offices, industrial plants, and smart city infrastructure across major global hubs."
  },
  {
    id: 3,
    question: "How does the Clarity Hub integration work with existing BMS?",
    answer: "The Clarity Hub uses API-first architecture to seamlessly connect with legacy Building Management Systems (BMS), overlaying our AI optimization without disrupting current operations."
  },
  {
    id: 4,
    question: "Are the carbon neutrality reports third-party verified?",
    answer: "Yes, all our carbon neutrality reports undergo rigorous auditing by independent, certified environmental agencies before being finalized."
  },
  {
    id: 5,
    question: "How do I access real-time energy consumption data?",
    answer: "You can access real-time data through the Executive Dashboard, which provides live telemetry and predictive analytics for all your connected facilities."
  },
  {
    id: 6,
    question: "What security protocols are in place for data handling?",
    answer: "We employ military-grade encryption, role-based access control, and continuous security monitoring to ensure all your facility data is protected."
  },
  {
    id: 7,
    question: "Can I customize my facility's energy optimization plan?",
    answer: "Absolutely. Our AI provides a baseline plan, but facility managers can adjust parameters based on specific operational requirements or tenant needs."
  }
];

export default function FAQ() {
  const [openId, setOpenId] = useState(1);

  return (
    <div className="min-h-screen bg-brand-obsidian text-zinc-100 font-sans relative overflow-hidden">
      {/* Background Effect */}
      <div className="absolute inset-0 z-0">
        <div className="absolute inset-0 bg-brand-obsidian/90 backdrop-blur-3xl" />
        {/* Subtle orange/copper glow from sides */}
        <div className="absolute top-1/4 left-0 w-64 h-full bg-orange-600/10 blur-[150px] mix-blend-screen" />
        <div className="absolute top-1/4 right-0 w-64 h-full bg-orange-600/10 blur-[150px] mix-blend-screen" />
      </div>

      {/* Header/Nav */}
      <nav className="relative z-10 flex items-center justify-between px-8 py-6">
        <div className="flex items-center gap-2">
          {/* Logo Placeholder */}
          <div className="w-8 h-8 text-brand-cyan">
             <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>
          </div>
          <span className="text-2xl font-bold tracking-tight">BeeCarbonit <span className="font-normal text-zinc-400">FAQ - Clarity Hub</span></span>
        </div>
      </nav>

      <main className="relative z-10 container mx-auto px-6 py-12 max-w-4xl">
        <h1 className="text-3xl font-semibold mb-8 text-white">Accordion</h1>
        
        <div className="flex flex-col gap-4">
          {faqItems.map((item) => {
            const isOpen = openId === item.id;
            return (
              <div 
                key={item.id}
                className={`rounded-xl border transition-all duration-300 overflow-hidden ${
                  isOpen 
                    ? 'border-brand-cyan/50 bg-brand-cyan/5 shadow-[0_0_20px_rgba(0,242,255,0.15)]' 
                    : 'border-white/10 bg-white/5 hover:bg-white/10'
                } backdrop-blur-xl`}
              >
                <button
                  onClick={() => setOpenId(isOpen ? null : item.id)}
                  className="w-full flex items-center justify-between p-6 text-left"
                >
                  <span className={`text-lg font-medium transition-colors ${isOpen ? 'text-brand-cyan' : 'text-zinc-200'}`}>
                    {item.question}
                  </span>
                  {isOpen ? (
                    <ChevronUp className="text-brand-cyan" size={20} />
                  ) : (
                    <ChevronDown className="text-zinc-400" size={20} />
                  )}
                </button>
                
                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3 }}
                    >
                      <div className="px-6 pb-6 text-zinc-300 leading-relaxed">
                        {item.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </main>

      <footer className="relative z-10 text-center py-8 text-sm text-zinc-500">
        <div className="flex justify-center gap-6 mb-4">
          <a href="#" className="hover:text-zinc-300 transition-colors">About</a>
          <a href="#" className="hover:text-zinc-300 transition-colors">Contact</a>
          <a href="#" className="hover:text-zinc-300 transition-colors">Privacy Policy</a>
        </div>
        <p>Copyright © 2024 BeeCarbonit. All rights reserved.</p>
      </footer>
    </div>
  );
}
